//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public string MaCV { get; set; }
        public string TenCV { get; set; }
        public Nullable<double> LuongCB { get; set; }
    }
}
