//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public Nullable<System.DateTime> TGLap { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string UserName { get; set; }
        public string TrangThai { get; set; }
        public string MaUD { get; set; }
    }
}
