//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucTap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class quanlytrangsucEntities1 : DbContext
    {
        public quanlytrangsucEntities1()
            : base("name=quanlytrangsucEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DbSet<ChiTietPN> ChiTietPNs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CTPhanQuyen> CTPhanQuyens { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiT> LoaiTS { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<Thang> Thangs { get; set; }
        public virtual DbSet<ThuongPhat> ThuongPhats { get; set; }
        public virtual DbSet<TrangSuc> TrangSucs { get; set; }
        public virtual DbSet<UuDai> UuDais { get; set; }
    
        [DbFunction("quanlytrangsucEntities1", "dsnhanvien")]
        public virtual IQueryable<dsnhanvien_Result> dsnhanvien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<dsnhanvien_Result>("[quanlytrangsucEntities1].[dsnhanvien]()");
        }
    
        public virtual int deleteNhanVien(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteNhanVien", manvParameter);
        }
    
        public virtual int insertCTPN(string maPN, Nullable<int> soLuong, Nullable<double> giaNhap, string tenTS, string maLoai, byte[] hinhAnh, string donVi)
        {
            var maPNParameter = maPN != null ?
                new ObjectParameter("MaPN", maPN) :
                new ObjectParameter("MaPN", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(double));
    
            var tenTSParameter = tenTS != null ?
                new ObjectParameter("TenTS", tenTS) :
                new ObjectParameter("TenTS", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(byte[]));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertCTPN", maPNParameter, soLuongParameter, giaNhapParameter, tenTSParameter, maLoaiParameter, hinhAnhParameter, donViParameter);
        }
    }
}
