//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public string MaPN { get; set; }
        public string MaNCC { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> ThơiGianLap { get; set; }
        public Nullable<double> TongTien { get; set; }
    }
}
