//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucTap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thang
    {
        public int Thang1 { get; set; }
        public string MaNV { get; set; }
        public Nullable<double> Luong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
